### ISSUE TITLE
readme images

### ISSUE THREAD

**Issue by nj-io** [FACN3/prioritiseMe#6]

**Comment by ionush** [comment]
blob:https://web.whatsapp.com/a11fe4b0-b347-4874-b5e8-8d64f2b30361

**Comment by nj-io** [comment]
![dddb4cb5-7b65-4162-8cb9-b4fd7c08b49e](https://user-images.githubusercontent.com/26359601/33603904-d4d5f418-d9bc-11e7-8560-059b2a9648a2.jpeg)

**Comment by nj-io** [comment]
![876bdd98-eb2d-4cc4-acfa-0296ec0bdfec](https://user-images.githubusercontent.com/26359601/33603911-da18bc08-d9bc-11e7-9f5d-766948c8580f.jpeg)

**Comment by nj-io** [comment]
![screenshot from 2017-12-05 12-50-42](https://user-images.githubusercontent.com/26359601/33603919-e223dae0-d9bc-11e7-8be4-c4c6fc49d2eb.png)
